### ISSUE TITLE
Setup Github Actions !! 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [rohan-kulkarni-25/Learn-GITHUB#28]
<ul>
<li>Fork the Repository</li>
<li>In your repository open folder `.github`</li>
<li>Go into folder `workflows`</li>
<li>Create a new file `greeting.yml`</li>
<li>Paste the content given below</li><br>
  
name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi👋 thanks for creating an issue on my Readme Profile !!, Will get back to you soon !! Your Contribution matters a lot for me ! "
          pr-message: "🎉Congratulations!!🎉 for making PR , I will review it soon !! Your Contribution matters a lot for me !"

<li>Commit those changes</li>
<li>Create Pull Request</li>
</ul>

Great You got 🟩 for Today !!

**Comment by sarthakjdev** [comment]
Can I work on this ?
