### ISSUE TITLE
Learner Addition

### ISSUE THREAD

**Issue by Aiswarika** [rohan-kulkarni-25/Learn-GITHUB#37]
Enter Details Below !

Github Username :- Aiswarika
Your Name :- Aiswarika

Thanks !!!

**Comment by rohan-kulkarni-25** [comment]
Hey, @Aiswarika  Thanks for creating the Issue !! You can make suggested changes and come up with a Pr will be glad to get it merged !!

**Comment by Aiswarika** [comment]
Thank you!
